#
# $Id: Makefile.nmake 35750 2011-02-02 02:52:53Z wmeier $
#

include ../config.nmake
include <win32.mak>

wireshark.manifest:	nsis/wireshark.nsi ws-manifest.pl
	$(PERL) ws-manifest.pl nsis/wireshark.nsi > $@	

clean:
	rm -rf wireshark.manifest

distclean:	clean
	
maintainer-clean:	distclean
	
