## Makefile for building wireshark.exe with Microsoft C and nmake
## Use: $(MAKE) /$(MAKEFLAGS) -f makefile.nmake
#
# $Id: Makefile.nmake 21182 2007-03-25 15:37:03Z ulfl $

include ..\..\config.nmake

all : TPG.pm

clean:
	rm -f TPG.pm tpg.output

distclean: clean

maintainer-clean: distclean
